### ISSUE TITLE
When editing shouts on the shoutbox.

### ISSUE THREAD

**Issue by RaidForums** [martec/Miuna-Shoutbox-Server-Openshift-#6]
After finding out that you can edit your messages on the shoutbox with no flood protection you can run scripts to crash a shoutbox by editing your messages really fast causing shoutbox to crash.

**Comment by martec** [comment]
you can select what group can edit shout.

**Comment by RaidForums** [comment]
You know that is not a fix right?
Might aswell just remove the whole feature of editing messages then.

You just cant be asked to fix anything like come on dude.
